# Generated by Django 4.1.3 on 2022-11-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rforce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='email',
            new_name='user_email',
        ),
    ]
