# Generated by Django 4.1.3 on 2022-11-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rforce', '0002_rename_email_userinfo_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_email',
        ),
    ]
